# Generated by Django 3.1.7 on 2021-02-26 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.BigIntegerField()),
                ('address', models.CharField(max_length=150)),
                ('certificate', models.ImageField(upload_to='')),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='current_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
                ('state', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('market', models.CharField(max_length=50)),
                ('commodity', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=50)),
                ('arrival_data', models.DateField()),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('model_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantity', models.CharField(max_length=30)),
                ('deadline', models.CharField(max_length=20)),
                ('commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.commodity')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.company')),
            ],
        ),
    ]
